# certain definitions we can use

MAX_BRIDGE_CAPACITY = 3 
WATER = " "
SINGLE_HORIZONTAL = '-',
SINGLE_VERTICAL = '|',
DOUBLE_HORIZONTAL = '=',
DOUBLE_VERTICAL = '"',
TRIPLE_HORIZONTAL = 'E',
TRIPLE_VERTICAL = '#'

    
    